### ISSUE TITLE
Regression: ^1.39.1 seems to make sdk.generation.getGenerationById requests to timeout

### ISSUE THREAD

**Issue by ejkkan** [Leonardo-Interactive/leonardo-ts-sdk#39]
I've just updated to version `^1.39.1` and after updating it seems all requests I make with `sdk.generation.getGenerationById` reaches a timeout.

```
const awaitImages = async (gId: string) => {
  return new Promise<{ images: any[]; prompt: string }>((resolve, reject) => {
    const intervalId = setInterval(async () => {
      console.log('Checking checking for images...');
      try {
        const response = await sdk.generation.getGenerationById({ id: gId });

        const generation =
          response.getGenerationById200ApplicationJSONObject?.generationsByPk;

        if (
          generation?.generatedImages &&
          generation?.generatedImages?.length > 0
        ) {
          console.log('Found images!');
          clearInterval(intervalId);
          return resolve({
            images: generation.generatedImages.map(
              (imageGeneration) => imageGeneration.url
            ),
            prompt: generation.prompt,
          });
        }
        console.log('Not ready yet...');
      } catch (error) {
        clearInterval(intervalId);
        reject('Waiting for images error: ', error);
      }
    }, 10000);
  });
};
```

After triggering a generation of images, I run this function in order to await the generated images with the jobs generationId.

Seems to be a regression since this worked fine in `1.28.1`.

**Comment by ejkkan** [comment]
Anyone from the Leonardo team who could acknowledge this?

**Comment by ejkkan** [comment]
@anuraagnalluri 
I've created this example for most of the issues I've reported. [See here](https://github.com/ejkkan/leonardo-ai-template/tree/master) 
So please config it to make the setup relevant for each issue.
Notice that I'm using v1.28 specifically because of functionality being broken [as mentioned in](https://github.com/Leonardo-Interactive/leonardo-ts-sdk/issues/39)

**Comment by anuraagnalluri** [comment]
@ejkkan Reposting from Slack:
Hi team, do you have a test API key I can use for testing our SDK against the Leonardo API? I signed up for an account, but when I access Settings > User API, the tab is greyed out and in beta. Any help here would be appreciated, so we can get to reproducing your error.

**Comment by ejkkan** [comment]
Maybe you need a paying sub for API usage?
What slack channel is that? Any chance I can get in on the fun? 🙈

**Comment by anuraagnalluri** [comment]
We're using slack-connect, so it may be differently named in your workspace, but it's called `leonardo-speakeasy` in ours. Just re-posting the same information there I'm communicating with you through these issues. Is there anyway we can get a free temporary key so we can test this for you?

**Comment by ejkkan** [comment]
Got this working, it was a breaking change made around 1.29.x.
The SDK did not handle the old case and still sent it as a payload to the API, making the API fail.
