### ISSUE TITLE
A new version is being published every hour

### ISSUE THREAD

**Issue by nexdrew** [Leonardo-Interactive/leonardo-ts-sdk#74]
Ever since the [v2.3.0 release](https://github.com/Leonardo-Interactive/leonardo-ts-sdk/releases/tag/v2.3.0), some automated process seems to be generating a new release of this SDK library every hour.

It looks like the v2.3.0 release was possibly the last intended release, but then starting with [v2.4.0](https://github.com/Leonardo-Interactive/leonardo-ts-sdk/releases/tag/v2.4.0) onwards (up to v2.28.0 by the time of this writing) a new release has been published automatically every hour on the hour.

I don't know what changed between the v2.2.1 release on 2023-12-18 20:02:01 and the v2.3.0 release on 2024-01-04 13:19:55 that might have started this, but I suspect the ["Generate_And_Publish" GitHub Actions workflow](https://github.com/Leonardo-Interactive/leonardo-ts-sdk/blob/bc88fa516639b16544dff518da6ed12c15602706/.github/workflows/speakeasy_sdk_generate.yml) that runs on a schedule is to blame.

I am only assuming that creating a new release (and publishing a new version to npm) every hour is not what is intended, but perhaps I am wrong. Please look into this and let us know if this is intentional.

**Comment by PNRxA** [comment]
Thanks for the heads up! This should be fixed now.
