### ISSUE TITLE
Phoenix request requires sd_version to be "PHOENIX" (don't have this option in latest package)

### ISSUE THREAD

**Issue by Rot4tion** [Leonardo-Interactive/leonardo-ts-sdk#86]
@leonardo-ai/sdk 4.16.0

req:
```
leonardoai.createGeneration({
  alchemy: true,
  height: 896,
  modelId: '6b645e3a-d64f-4341-a6d8-7a3690fbf042',
  num_images: 1,
  presetStyle: 'LEONARDO',
  prompt: 'The design features a humorous ghost with an unimpressed expression, crossed arms, and the text "THIS IS BOO SHEET" above it in a bold, distressed font. The background consists of a retro-style, faded, sunset color palette with horizontal stripes, adding a vintage aesthetic. The ghost illustration has a distressed texture to complement the worn-out, vintage look of the design. The overall tone is playful and sarcastic, suitable for Halloween or humorous apparel.\' }',
  width: 896,
  scheduler: 'LEONARDO',
  sd_version: 'SDXL_LIGHTNING'
})
  .then(({ data }) => console.log(data))
  .catch(err => console.error(err));
```
  
 res:
```
  {
  "error": "Phoenix request requires sd_version to be PHOENIX.",
  "path": "$",
  "code": "unexpected"
}
```

sd_version don't have PHOENIX option
Tried:
- left sd_version default and force request with "PHOENIX" success but  response validation failed when 
` await this.leonardo.image.getGenerationById(payload.id);`
error
```
StatusCode:: 500, Message:: Response validation failed: [
  {
    "received": "PHOENIX",
    "code": "invalid_enum_value",
    "options": [
      "v1_5",
      "v2",
      "v3",
      "SDXL_0_8",
      "SDXL_0_9",
      "SDXL_1_0",
      "SDXL_LIGHTNING"
    ],
    "path": [
      "object",
      "generations_by_pk",
      "sdVersion"
    ],
    "message": "Invalid enum value. Expected 'v1_5' | 'v2' | 'v3' | 'SDXL_0_8' | 'SDXL_0_9' | 'SDXL_1_0' | 'SDXL_LIGHTNING', 
received 'PHOENIX'"
  }
]

```

**Comment by pcintra11** [comment]
Ii have the same problem.

**Comment by mecsantos** [comment]
Hi @Rot4tion @pcintra11 , please try not specifying sd_version. If you specify the model, no need to specify sd_version.

**Comment by dankiCodeBusiness** [comment]
Same problem here, and I'm not specifying the sdkVersion

**Comment by mecsantos** [comment]
Hi @peace-furniture , the only input for getting image generation by ID should be just the generation ID.

In terms of an update, it's a holiday in Australia today. We'll flag to engineering this week and will keep you posted on timing.

This was open for a week because we don't monitor issues here. We probably only noticed when it got flagged via support@leonardo.ai.

We are happy to process refunds, just kindly send this thread via our support. We apologize for the trouble and delay in your development.

**Comment by silvamarcel** [comment]
Hey @peace-furniture, @Rot4tion and @pcintra11, I will be publishing a fix to add the missing type soon.

**Comment by ronvoluted** [comment]
@Rot4tio, @pcintra11, @dankiCodeBusiness and @peace-furniture please find @silvamarcel's changes in version `4.18.1`.

**Comment by pcintra11** [comment]
Works now! Tks!

**Comment by silvamarcel** [comment]
Closing the issue for now, if anything comes up, please reach out to us.

**Comment by microooji** [comment]
@silvamarcel @ronvoluted I get the same problem if I use the Flux model, add FLUX as well.

`errors: [
      {
        received: 'FLUX',
        code: 'invalid_enum_value',
        options: [
          'v1_5',
          'v2',
          'v3',
          'SDXL_0_8',
          'SDXL_0_9',
          'SDXL_1_0',
          'SDXL_LIGHTNING',
          'PHOENIX'
        ],
        path: [ 'object', 'generations_by_pk', 'sdVersion' ],
        message: "Invalid enum value. Expected 'v1_5' | 'v2' | 'v3' | 'SDXL_0_8' | 'SDXL_0_9' | 'SDXL_1_0' | 'SDXL_LIGHTNING' | 'PHOENIX', received 'FLUX'"
      }
    ]
`

**Comment by mecsantos** [comment]
We made an update, can you please try the latest version?

For new issues, please open a new one. It's also faster if you contact our support team, you can send a link to your issue.

**Comment by microooji** [comment]
> We made an update, can you please try the latest version?

it works, thanks
